parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony
    database_user: symfony
    database_password: symfony
    mailer_transport: gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: tuliofritz
    mailer_password: +*genotipo28*
    locale: en
    secret: d2310248b491ba18e1151066a7d3b9bd104
    database_path: null